export const CHANGE_CURRENT_BOARD_GAME = 'CHANGE_CURRENT_BOARD_GAME';
export const GET_ALL_BOARD_GAMES = 'GET_ALL_BOARD_GAMES';
export const TRY_TO_GET_ALL_BOARD_GAMES = 'GET_ALL_BOARD_GAMES';
export const ADD_NEW_BOARD_GAME = 'ADD_NEW_BOARD_GAME';
export const DELETE_BOARD_GAME = 'DELETE_BOARD_GAME';
